/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexiones;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import static ventanas.Login.user;

/**
 *
 * @author MINEDUCYT
 */
public class InformacionUsuario extends javax.swing.JFrame {

    String user;
    String update;
    int ID;

    /**
     * Creates new form InformacionUsuario
     */
    public InformacionUsuario() {
        initComponents();
        setLocationRelativeTo(null);
        user = Login.user;
        update = GestionUsuarios.userU;
        setResizable(false);
        setTitle("Gestion de Usuarios - User: " + user);
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        ImageIcon Wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(Wallpaper.getImage().getScaledInstance(LabelWallpaper.getWidth(),
                LabelWallpaper.getHeight(), Image.SCALE_DEFAULT));

        LabelWallpaper.setIcon(icono);
        this.repaint();

        LabelNombre.setText("Información del usuario " + update);

        try {
            Connection cn = Conexiones.conexion();
            PreparedStatement pst = cn.prepareStatement(
                    "select * from usuarios where Username = '" + update + "'");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                ID = rs.getInt("ID");
                TxtNombre.setText(rs.getString("NombreUsuario"));
                TxtMail.setText(rs.getString("Email"));
                TxtTelefono.setText(rs.getString("Telefono"));
                TxtUser.setText(rs.getString("UserName"));
                TxtRegistrado.setText(rs.getString("Registado"));

                CmbNivel.setSelectedItem(rs.getString("Nivel"));
                CmbEstatus.setSelectedItem(rs.getString("Estatus"));
            }
            cn.close();
        } catch (Exception e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(null, "Error porfavor contacte al administrador");
        }
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource(
                "images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelNombre = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        TxtMail = new javax.swing.JTextField();
        Telefono = new javax.swing.JLabel();
        TxtTelefono = new javax.swing.JTextField();
        Permiso = new javax.swing.JLabel();
        CmbNivel = new javax.swing.JComboBox<>();
        Username = new javax.swing.JLabel();
        TxtUser = new javax.swing.JTextField();
        Estatus = new javax.swing.JLabel();
        CmbEstatus = new javax.swing.JComboBox<>();
        Registrado = new javax.swing.JLabel();
        TxtRegistrado = new javax.swing.JTextField();
        Actualizar = new javax.swing.JButton();
        contaseña = new javax.swing.JButton();
        LabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelNombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        LabelNombre.setText("Informacion del Usuario");
        getContentPane().add(LabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        Nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Nombre.setText("Nombre:");
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        TxtNombre.setBackground(new java.awt.Color(153, 153, 255));
        TxtNombre.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        TxtNombre.setForeground(new java.awt.Color(255, 255, 255));
        TxtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, -1));

        Email.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setText("Email:");
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        TxtMail.setBackground(new java.awt.Color(153, 153, 255));
        TxtMail.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        TxtMail.setForeground(new java.awt.Color(255, 255, 255));
        TxtMail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtMail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(TxtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, -1));

        Telefono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Telefono.setForeground(new java.awt.Color(255, 255, 255));
        Telefono.setText("Telefono:");
        getContentPane().add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        TxtTelefono.setBackground(new java.awt.Color(153, 153, 255));
        TxtTelefono.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        TxtTelefono.setForeground(new java.awt.Color(255, 255, 255));
        TxtTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtTelefono.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(TxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 210, -1));

        Permiso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Permiso.setForeground(new java.awt.Color(255, 255, 255));
        Permiso.setText("Permisos de:");
        getContentPane().add(Permiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        CmbNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Capturista", "Tecnico" }));
        getContentPane().add(CmbNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        Username.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("Usename");
        getContentPane().add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        TxtUser.setBackground(new java.awt.Color(153, 153, 255));
        TxtUser.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        TxtUser.setForeground(new java.awt.Color(255, 255, 255));
        TxtUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(TxtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 210, -1));

        Estatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Estatus.setForeground(new java.awt.Color(255, 255, 255));
        Estatus.setText("Estado:");
        getContentPane().add(Estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        CmbEstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        getContentPane().add(CmbEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, -1));

        Registrado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Registrado.setForeground(new java.awt.Color(255, 255, 255));
        Registrado.setText("Registrado por:");
        getContentPane().add(Registrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        TxtRegistrado.setBackground(new java.awt.Color(153, 153, 255));
        TxtRegistrado.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        TxtRegistrado.setForeground(new java.awt.Color(255, 255, 255));
        TxtRegistrado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtRegistrado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TxtRegistrado.setEnabled(false);
        getContentPane().add(TxtRegistrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 210, -1));

        Actualizar.setBackground(new java.awt.Color(153, 153, 255));
        Actualizar.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Actualizar.setForeground(new java.awt.Color(255, 255, 255));
        Actualizar.setText("Restaurar contraseña");
        Actualizar.setBorder(null);
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 210, 35));

        contaseña.setBackground(new java.awt.Color(153, 153, 255));
        contaseña.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        contaseña.setForeground(new java.awt.Color(255, 255, 255));
        contaseña.setText("Actualizar");
        contaseña.setBorder(null);
        contaseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contaseñaActionPerformed(evt);
            }
        });
        getContentPane().add(contaseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 210, 35));
        getContentPane().add(LabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contaseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contaseñaActionPerformed

        int Statuscmb, permisoscmb, Validacion = 0;
        String Nombre, Mail, User, Pass, Telefono, SPermisos = "", SEstatus = "";

        Nombre = TxtNombre.getText().trim();
        Mail = TxtMail.getText().trim();
        User = TxtUser.getText().trim();
        Telefono = TxtTelefono.getText().trim();
        permisoscmb = CmbNivel.getSelectedIndex() + 1;
        Statuscmb = CmbEstatus.getSelectedIndex() + 1;

        if (Nombre.equals("")) {
            TxtNombre.setBackground(Color.red);
            Validacion++;
        } else {
            TxtNombre.setBackground(Color.BLUE);
        }
        if (Mail.equals("")) {
            TxtMail.setBackground(Color.red);
            Validacion++;
        } else {
            TxtMail.setBackground(Color.BLUE);
        }
        if (User.equals("")) {
            TxtUser.setBackground(Color.red);
            Validacion++;
        } else {
            TxtUser.setBackground(Color.BLUE);
        }
        if (Telefono.equals("")) {
            TxtTelefono.setBackground(Color.red);
            Validacion++;
        } else {
            TxtTelefono.setBackground(Color.BLUE);
        }
        if (Validacion == 0) {

            if (permisoscmb == 1) {
                SPermisos = "Administrador";
            } else if (permisoscmb == 2) {
                SPermisos = "Capturista";
            } else if (permisoscmb == 3) {
                SPermisos = "Tecnico";
            }
            if (Statuscmb == 1) {
                SEstatus = "Activo";
            } else if (Statuscmb == 2) {
                SEstatus = "Inactivo";
            }

            try {
                Connection cn = Conexiones.conexion();
                PreparedStatement pst = cn.prepareStatement(
                        "select Username from usuarios where Username = '" + User + "' and not ID = '" + ID + "'");

                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    TxtUser.setBackground(Color.red);
                    JOptionPane.showMessageDialog(null, "El nombre de usuario ya esta ocupado");
                } else {
                    Connection cn2 = Conexiones.conexion();
                    PreparedStatement pst2 = cn.prepareStatement(
                            "Update usuarios set NombreUsuario=?, Email=?, Telefono=?, Username=?, Nivel=?, Estatus=? "
                            + "where ID = '" + ID + "'");

                    pst2.setString(1, Nombre);
                    pst2.setString(2, Mail);
                    pst2.setString(3, Telefono);
                    pst2.setString(4, User);
                    pst2.setString(5, SPermisos);
                    pst2.setString(6, SEstatus);

                    pst2.executeUpdate();
                    cn2.close();
                    JOptionPane.showMessageDialog(null, "Actualizacion exitosa");
                     this.dispose();
                }
            } catch (Exception e) {
                System.out.println(e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
        }
    }//GEN-LAST:event_contaseñaActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
               new Restaurar().setVisible(true);
    }//GEN-LAST:event_ActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JComboBox<String> CmbEstatus;
    private javax.swing.JComboBox<String> CmbNivel;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Estatus;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelWallpaper;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Permiso;
    private javax.swing.JLabel Registrado;
    private javax.swing.JLabel Telefono;
    private javax.swing.JTextField TxtMail;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtRegistrado;
    private javax.swing.JTextField TxtTelefono;
    private javax.swing.JTextField TxtUser;
    private javax.swing.JLabel Username;
    private javax.swing.JButton contaseña;
    // End of variables declaration//GEN-END:variables
}
