/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexiones;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;
import static ventanas.Administrador.sesion;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author MINEDUCYT
 */
public class InsertarEquipos extends javax.swing.JFrame {

    String user, n;
    int cliente;

    /**
     * Creates new form GestondeEquipos
     */
    public InsertarEquipos() {
        initComponents();
        cliente = InformacionCliente.id;
        n = InformacionCliente.n;
        user = Login.user;
        sesion = Administrador.sesion;
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setSize(630, 445);
        setResizable(false);
        setTitle("Añadir equipo para " + n + " - User: " + user
        );
        this.setLocationRelativeTo(null);

        ImageIcon Wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(Wallpaper.getImage().getScaledInstance(LabelWallpaper.getWidth(),
                LabelWallpaper.getHeight(), Image.SCALE_DEFAULT));

        LabelWallpaper.setIcon(icono);
        this.repaint();

        TxtCliente.setText(n);

    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource(
                "images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ingresar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaObservacion = new javax.swing.JTextArea();
        LabelNombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TxtCliente = new javax.swing.JTextField();
        TxtModelo = new javax.swing.JTextField();
        TxtNumSerie = new javax.swing.JTextField();
        CmbTipo = new javax.swing.JComboBox<>();
        CmbMarca = new javax.swing.JComboBox<>();
        LabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ingresar1.setBackground(new java.awt.Color(153, 153, 240));
        Ingresar1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        Ingresar1.setForeground(new java.awt.Color(255, 255, 255));
        Ingresar1.setText("Ingresar Equipo");
        Ingresar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Ingresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingresar1ActionPerformed(evt);
            }
        });
        getContentPane().add(Ingresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 210, 35));

        AreaObservacion.setColumns(20);
        AreaObservacion.setRows(5);
        jScrollPane1.setViewportView(AreaObservacion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 330, 230));

        LabelNombre.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        LabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        LabelNombre.setText("Registro de Equipo");
        LabelNombre.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(LabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre del Cliente:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo de Equipo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Marca:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Modelo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Numero de serie:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Daño reportado y Observaciones");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        TxtCliente.setBackground(new java.awt.Color(153, 153, 255));
        TxtCliente.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        TxtCliente.setForeground(new java.awt.Color(255, 255, 255));
        TxtCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TxtCliente.setEnabled(false);
        getContentPane().add(TxtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 210, -1));

        TxtModelo.setBackground(new java.awt.Color(153, 153, 255));
        TxtModelo.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        TxtModelo.setForeground(new java.awt.Color(255, 255, 255));
        TxtModelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtModelo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(TxtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 210, -1));

        TxtNumSerie.setBackground(new java.awt.Color(153, 153, 255));
        TxtNumSerie.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        TxtNumSerie.setForeground(new java.awt.Color(255, 255, 255));
        TxtNumSerie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtNumSerie.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(TxtNumSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 210, -1));

        CmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "Desktop", "Impresora", "Multi funcional" }));
        getContentPane().add(CmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 210, -1));

        CmbMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acer", "Alienware", "Apple", "Asus", "Brother", "Dell", "Hp", "Lenovo" }));
        getContentPane().add(CmbMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 210, -1));
        getContentPane().add(LabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ingresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingresar1ActionPerformed

        String modelo, numero, stipo = "", smarca = "", dia, mes, año, observacion;
        int tipo, marca, solo = 0, ID;

        modelo = TxtModelo.getText().trim();
        numero = TxtNumSerie.getText().trim();
        tipo = CmbTipo.getSelectedIndex();
        marca = CmbMarca.getSelectedIndex();
        observacion = AreaObservacion.getText().trim();
        ID = cliente;

        Calendar cal = Calendar.getInstance();

        dia = Integer.toString(cal.get(Calendar.DATE));
        mes = Integer.toString(cal.get(Calendar.MONTH));
        año = Integer.toString(cal.get(Calendar.YEAR));

        if (modelo.equals("")) {
            TxtModelo.setBackground(Color.red);
            solo++;
        } else {
        }

        if (numero.equals("")) {
            TxtNumSerie.setBackground(Color.red);
            solo++;
        } else {
        }
        if (observacion.equals("")) {
            AreaObservacion.setBackground(Color.red);
            solo++;
        } else {
        }
        if (tipo == 0) {
            stipo = "Laptop";
        } else if (tipo == 1) {
            stipo = "Desktop";
        } else if (tipo == 2) {
            stipo = "Impresora";
        } else if (tipo == 3) {
            stipo = "Multi funcion";
        }

        if (marca == 0) {
            smarca = "Acer";
        } else if (marca == 1) {
            smarca = "Alienware";
        } else if (marca == 2) {
            smarca = "Apple";
        } else if (marca == 3) {
            smarca = "Asus";
        } else if (marca == 4) {
            smarca = "Brother";
        } else if (marca == 5) {
            smarca = "Dell";
        } else if (marca == 6) {
            smarca = "Hp";
        } else if (marca == 7) {
            smarca = "Lenovo";
        }
        if (solo == 0) {
            try {
                Connection cn = Conexiones.conexion();
                PreparedStatement pst = cn.prepareStatement(
                        "insert into equipo values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");

                pst.setInt(1, 0);
                pst.setInt(2, ID);
                pst.setString(3, stipo);
                pst.setString(4, smarca);
                pst.setString(5, modelo);
                pst.setString(6, numero);
                pst.setString(7, dia);
                pst.setString(8, mes);
                pst.setString(9, año);
                pst.setString(10, observacion);
                pst.setString(11, "Nuevo Ingreso");
                pst.setString(12, user);
                pst.setString(13, "Sin Comentarios");
                pst.setString(14, "Nadie");

                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Registro exitoso");

                this.dispose();
            } catch (Exception e) {
            }
        } else {
            JOptionPane.showMessageDialog(null, "Error, llene todos los campos");
        }
    }//GEN-LAST:event_Ingresar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertarEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertarEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertarEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertarEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertarEquipos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaObservacion;
    private javax.swing.JComboBox<String> CmbMarca;
    private javax.swing.JComboBox<String> CmbTipo;
    private javax.swing.JButton Ingresar1;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelWallpaper;
    private javax.swing.JTextField TxtCliente;
    private javax.swing.JTextField TxtModelo;
    private javax.swing.JTextField TxtNumSerie;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
